### ISSUE TITLE
Remove Dead Code: also removes variable assignments used in compact function

### ISSUE THREAD

**Issue by proclame** [laravel-shift/workbench-issues#21] opened 2021-07-14 14:39 UTC
**Desktop:**
 - OS: Mac
 - OS Version: Big Sur
 - App Version: 0.4.1

**Describe the bug**
When running the new "Remove Dead Code" worker, a variable assignment that is used in a compact() call afterwards is also removed.

**Before**
```php
$transports = $driver->transports();

return view('drivers.processTransports', compact(['driver', 'transports', 'driverLinks', 'period']));
```

**After**
```php
$driver->transports();

return view('drivers.processTransports', compact(['driver', 'transports', 'driverLinks', 'period']));
```

**Comment by jasonmccreary** [comment] 2021-07-14 14:44
@jessarcher, I believe you solved this before. Maybe a regression?

**Comment by jessarcher** [comment] 2021-07-15 04:44
It turns out Rector only supports PHP's `compact(string $var_name, string ...$var_names)` syntax and ignores the alternative array syntax that is being used here.

I have PR'd Rector to support the full recursive array syntax which will hopefully be merged and released soon.

**Comment by jasonmccreary** [comment] 2021-07-21 13:57
@proclame this should be resolved in the latest release (0.4.6). Let us know.

**Closed as completed by jasonmccreary** 2021-07-21 13:57 UTC
Labels: bug, in progress

**Comment by proclame** [comment] 2021-07-21 14:10
@jasonmccreary Confirmed! I ran it again (with the new version) on the same codebase, and worked as expected now!
Thanks @jessarcher :-)
